CREATE TABLE IF NOT EXISTS druid_datasource (
	id SERIAL8 NOT NULL,
	domain varchar(45) NOT NULL, 
	app varchar(45) NOT NULL, 
	cluster varchar(45) NOT NULL, 
	host varchar(128), 
	pid integer NOT NULL,
	collectTime TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
	name varchar(256), 
	dbType varchar(256), 
	driverClassName varchar(256), 
	activeCount integer,
	activePeak integer,
	activePeakTime bigint,
	poolingCount integer,
	poolingPeak integer,
	poolingPeakTime bigint,
	connectCount bigint,
	closeCount bigint,
	waitThreadCount bigint,
	notEmptyWaitCount bigint,
	notEmptyWaitNanos bigint,
	logicConnectErrorCount bigint,
	physicalConnectCount bigint,
	physicalCloseCount bigint,
	physicalConnectErrorCount bigint,
	executeCount bigint,
	errorCount bigint,
	commitCount bigint,
	rollbackCount bigint,
	pstmtCacheHitCount bigint,
	pstmtCacheMissCount bigint,
	startTransactionCount bigint,
	txn_0_1 bigint,
	txn_1_10 bigint,
	txn_10_100 bigint,
	txn_100_1000 bigint,
	txn_1000_10000 bigint,
	txn_10000_100000 bigint,
	txn_more bigint,
	clobOpenCount bigint,
	blobOpenCount bigint,
	sqlSkipCount bigint,
	PRIMARY KEY (id)
);

CREATE INDEX druid_datasource_index ON druid_datasource (collectTime, domain, app);