CREATE TABLE IF NOT EXISTS druid_springmethod (
	id SERIAL8 NOT NULL, 
	domain varchar(45) NOT NULL, 
	app varchar(45) NOT NULL, 
	cluster varchar(45) NOT NULL, 
	host varchar(128), 
	pid integer NOT NULL,
	collectTime TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
	className varchar(256), 
	signature varchar(256), 
	runningCount integer,
	concurrentMax integer,
	executeCount bigint,
	executeErrorCount bigint,
	executeTimeNano bigint,
	jdbcFetchRowCount bigint,
	jdbcUpdateCount bigint,
	jdbcExecuteCount bigint,
	jdbcExecuteErrorCount bigint,
	jdbcExecuteTimeNano bigint,
	jdbcCommitCount bigint,
	jdbcRollbackCount bigint,
	jdbcPoolConnectionOpenCount bigint,
	jdbcPoolConnectionCloseCount bigint,
	jdbcResultSetOpenCount bigint,
	jdbcResultSetCloseCount bigint,
	lastErrorClass varchar(256), 
	lastErrorMessage varchar(256), 
	lastErrorStackTrace varchar(256), 
	lastErrorTimeMillis bigint,
	h1 bigint,
	h10 bigint,
	h100 bigint,
	h1000 bigint,
	h10000 integer,
	h100000 integer,
	h1000000 integer,
	hmore integer,
	PRIMARY KEY (id)
);

CREATE INDEX druid_springmethod_index ON druid_springmethod (collectTime, domain, app);