CREATE TABLE IF NOT EXISTS druid_sql (
	id SERIAL8 NOT NULL, 
	domain varchar(45) NOT NULL, 
	app varchar(45) NOT NULL, 
	cluster varchar(45) NOT NULL, 
	host varchar(128), 
	pid integer NOT NULL,
	collectTime TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
	sqlHash bigint,
	dataSource varchar(256), 
	lastStartTime bigint,
	batchTotal bigint,
	batchToMax integer,
	execSuccessCount bigint,
	execNanoTotal bigint,
	execNanoMax bigint,
	running integer,
	concurrentMax integer,
	rsHoldTime bigint,
	execRsHoldTime bigint,
	name varchar(256), 
	file varchar(256), 
	dbType varchar(256), 
	execNanoMaxOccurTime bigint,
	errorCount bigint,
	errorLastMsg varchar(256), 
	errorLastClass varchar(256), 
	errorLastStackTrace varchar(256), 
	errorLastTime bigint,
	updateCount bigint,
	updateCountMax bigint,
	fetchRowCount bigint,
	fetchRowCountMax bigint,
	inTxnCount bigint,
	lastSlowParameters varchar(256), 
	clobOpenCount bigint,
	blobOpenCount bigint,
	readStringLength bigint,
	readBytesLength bigint,
	inputStreamOpenCount bigint,
	readerOpenCount bigint,
	h1 bigint,
	h10 bigint,
	h100 integer,
	h1000 integer,
	h10000 integer,
	h100000 integer,
	h1000000 integer,
	hmore integer,
	eh1 bigint,
	eh10 bigint,
	eh100 integer,
	eh1000 integer,
	eh10000 integer,
	eh100000 integer,
	eh1000000 integer,
	ehmore integer,
	f1 bigint,
	f10 bigint,
	f100 bigint,
	f1000 integer,
	f10000 integer,
	fmore integer,
	u1 bigint,
	u10 bigint,
	u100 bigint,
	u1000 integer,
	u10000 integer,
	umore integer,
	PRIMARY KEY (id)
);

CREATE INDEX druid_sql_index ON druid_sql (collectTime, domain, app);