CREATE TABLE IF NOT EXISTS druid_webapp (
	id SERIAL8 NOT NULL, 
	domain varchar(45) NOT NULL, 
	app varchar(45) NOT NULL, 
	cluster varchar(45) NOT NULL, 
	host varchar(128), 
	pid integer NOT NULL,
	collectTime TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
	contextPath varchar(256), 
	runningCount integer,
	concurrentMax integer,
	requestCount bigint,
	sessionCount bigint,
	jdbcFetchRowCount bigint,
	jdbcUpdateCount bigint,
	jdbcExecuteCount bigint,
	jdbcExecuteTimeNano bigint,
	jdbcCommitCount bigint,
	jdbcRollbackCount bigint,
	osMacOSXCount bigint,
	osWindowsCount bigint,
	osLinuxCount bigint,
	osSymbianCount bigint,
	osFreeBSDCount bigint,
	osOpenBSDCount bigint,
	osAndroidCount bigint,
	osWindows98Count bigint,
	osWindowsXPCount bigint,
	osWindows2000Count bigint,
	osWindowsVistaCount bigint,
	osWindows7Count bigint,
	osWindows8Count bigint,
	osAndroid15Count bigint,
	osAndroid16Count bigint,
	osAndroid20Count bigint,
	osAndroid21Count bigint,
	osAndroid22Count bigint,
	osAndroid23Count bigint,
	osAndroid30Count bigint,
	osAndroid31Count bigint,
	osAndroid32Count bigint,
	osAndroid40Count bigint,
	osAndroid41Count bigint,
	osAndroid42Count bigint,
	osAndroid43Count bigint,
	osLinuxUbuntuCount bigint,
	browserIECount bigint,
	browserFirefoxCount bigint,
	browserChromeCount bigint,
	browserSafariCount bigint,
	browserOperaCount bigint,
	browserIE5Count bigint,
	browserIE6Count bigint,
	browserIE7Count bigint,
	browserIE8Count bigint,
	browserIE9Count bigint,
	browserIE10Count bigint,
	browser360SECount bigint,
	deviceAndroidCount bigint,
	deviceIpadCount bigint,
	deviceIphoneCount bigint,
	deviceWindowsPhoneCount bigint,
	botCount bigint,
	botBaiduCount bigint,
	botYoudaoCount bigint,
	botGoogleCount bigint,
	botMsnCount bigint,
	botBingCount bigint,
	botSosoCount bigint,
	botSogouCount bigint,
	botYahooCount bigint,
	PRIMARY KEY (id)
);

CREATE INDEX druid_webapp_index ON druid_webapp (collectTime, domain, app);