CREATE TABLE IF NOT EXISTS druid_weburi (
	id SERIAL8 NOT NULL, 
	domain varchar(45) NOT NULL, 
	app varchar(45) NOT NULL, 
	cluster varchar(45) NOT NULL, 
	host varchar(128), 
	pid integer NOT NULL,
	collectTime TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
	uri varchar(256), 
	runningCount integer,
	concurrentMax integer,
	requestCount bigint,
	requestTimeNano bigint,
	jdbcFetchRowCount bigint,
	jdbcFetchRowPeak bigint,
	jdbcUpdateCount bigint,
	jdbcUpdatePeak bigint,
	jdbcExecuteCount bigint,
	jdbcExecuteErrorCount bigint,
	jdbcExecutePeak bigint,
	jdbcExecuteTimeNano bigint,
	jdbcCommitCount bigint,
	jdbcRollbackCount bigint,
	jdbcPoolConnectionOpenCount bigint,
	jdbcPoolConnectionCloseCount bigint,
	jdbcResultSetOpenCount bigint,
	jdbcResultSetCloseCount bigint,
	errorCount bigint,
	lastAccessTime TIMESTAMP(6) WITHOUT TIME ZONE,
	h1 bigint,
	h10 bigint,
	h100 bigint,
	h1000 bigint,
	h10000 integer,
	h100000 integer,
	h1000000 integer,
	hmore integer,
	PRIMARY KEY (id)
);

CREATE INDEX druid_weburi_index ON druid_weburi (collectTime, domain, app);